version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  deploy:
    executor:
      name: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            git pull
      - heroku/deploy-via-git
workflows:
    build:
      jobs:
        - build
    heroku_deploy:
      jobs:
        - deploy
