version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  pull:
    commands:
      - git pull
workflows:
    build:
      jobs:
        - build
        - pull
    heroku_deploy:
      jobs:
        - heroku/deploy-via-git
